/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package quickcount;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Mhd Sulhan
 */
public class MainWindow extends javax.swing.JFrame {

	/**
	 * Creates new form MainWindow
	 */
	public MainWindow() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tf_userName = new javax.swing.JTextField();
        l_userName = new javax.swing.JLabel();
        l_userPass = new javax.swing.JLabel();
        b_login = new javax.swing.JButton();
        pf_userPass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QuickCount :: Login");
        setResizable(false);

        tf_userName.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        l_userName.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        l_userName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        l_userName.setLabelFor(tf_userName);
        l_userName.setText("User Name :");

        l_userPass.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        l_userPass.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        l_userPass.setLabelFor(pf_userPass);
        l_userPass.setText("Password :");

        b_login.setText("Login");
        b_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_loginMouseClicked(evt);
            }
        });

        pf_userPass.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        pf_userPass.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(b_login)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(l_userName)
                            .addComponent(l_userPass))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_userName, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                            .addComponent(pf_userPass))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_userName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_userName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_userPass)
                    .addComponent(pf_userPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_login)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_loginMouseClicked
        String			u	= tf_userName.getText();
		String			p	= pf_userPass.getText();
		QuickCount		qc	= QuickCount.getInstance();
		DatabaseManager dbm = DatabaseManager.getInstance ();

		dbm.prepare (" select	A.id"
					+" ,		A.kelurahan_id"
					+" ,		D.nama			as kelurahan_nama"
					+" ,		A.kecamatan_id"
					+" ,		C.nama			as kecamatan_nama"
					+" ,		A.dapil_id"
					+" ,		B.nama			as dapil_nama"
					+" from		users		A"
					+" ,		dapil		B"
					+" ,		kecamatan	C"
					+" ,		kelurahan	D"
					+" where	A.nama			= ?"
					+" and		A.password		= ?"
					+" and		A.dapil_id		= B.id"
					+" and		A.kecamatan_id	= C.id"
					+" and		A.kelurahan_id	= D.id"
					);

		try {
			dbm._ps.setString(1, u);
			dbm._ps.setString(2, p);

			dbm.executePrepare ();

			if (! dbm._rs.next()) {
				JOptionPane.showMessageDialog(this, "User atau password anda salah!");
				return;
			}

			qc.user_id			= dbm._rs.getInt("id");
			qc.dapil_id			= dbm._rs.getInt("dapil_id");
			qc.kecamatan_id		= dbm._rs.getInt("kecamatan_id");
			qc.kelurahan_id		= dbm._rs.getInt("kelurahan_id");
			qc.dapil_nama		= dbm._rs.getString("dapil_nama");
			qc.kecamatan_nama	= dbm._rs.getString("kecamatan_nama");
			qc.kelurahan_nama	= dbm._rs.getString("kelurahan_nama");

			dbm.close ();

			qc.win_saksi = new WinSaksi();

			qc.win_saksi.setVisible(true);
			qc.win_main.setVisible(false);
		} catch (SQLException ex) {
			Logger.getLogger(DatabaseManager.class.getName()).log(Level.SEVERE, null, ex);
		}
    }//GEN-LAST:event_b_loginMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_login;
    private javax.swing.JLabel l_userName;
    private javax.swing.JLabel l_userPass;
    private javax.swing.JPasswordField pf_userPass;
    private javax.swing.JTextField tf_userName;
    // End of variables declaration//GEN-END:variables
}
