/*
 Copyright 2014 - Mhd Sulhan (m.shulhan@gmail.com)
 */

package quickcount;

import java.awt.BorderLayout;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.border.Border;

/**
 *
 * @author Mhd Sulhan <m.shulhan@gmail.com>
 */
public class PanelRekapSuara extends javax.swing.JPanel {
	private boolean on_load = true;

	/**
	 * Creates new form PanelRekapSuara
	 * @param type
	 */
	public PanelRekapSuara(int type) {
		initComponents();
		
		this.type.setValue(type);
		this.type.setVisible(false);
		
		this.on_load = true;
		
		ss_jumlah.setValue (0);
		ss_rusak.setValue (0);
		ss_sisa.setValue (0);
		ss_sah.setValue (0);
		ss_tidak_sah.setValue(0);

		loadData (type);
		
		this.on_load = false;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ss_jumlah = new javax.swing.JFormattedTextField();
        l_ss_jumlah = new javax.swing.JLabel();
        l_ss_rusak = new javax.swing.JLabel();
        ss_rusak = new javax.swing.JFormattedTextField();
        l_ss_sisa = new javax.swing.JLabel();
        ss_sisa = new javax.swing.JFormattedTextField();
        l_ss_sah = new javax.swing.JLabel();
        ss_sah = new javax.swing.JFormattedTextField();
        l_ss_tidak_sah = new javax.swing.JLabel();
        ss_tidak_sah = new javax.swing.JFormattedTextField();
        type = new javax.swing.JFormattedTextField();

        setToolTipText("");
        setName("Rekap Surat Suara"); // NOI18N

        ss_jumlah.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        ss_jumlah.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ss_jumlah.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                onChange(evt);
            }
        });

        l_ss_jumlah.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        l_ss_jumlah.setLabelFor(ss_jumlah);
        l_ss_jumlah.setText("Jumlah Surat Suara :");
        l_ss_jumlah.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        l_ss_rusak.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        l_ss_rusak.setLabelFor(ss_jumlah);
        l_ss_rusak.setText("Jumlah Surat Suara Rusak :");

        ss_rusak.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        ss_rusak.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ss_rusak.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                onChange(evt);
            }
        });

        l_ss_sisa.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        l_ss_sisa.setLabelFor(ss_jumlah);
        l_ss_sisa.setText("Jumlah Sisa Surat Suara :");

        ss_sisa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        ss_sisa.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ss_sisa.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                onChange(evt);
            }
        });

        l_ss_sah.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        l_ss_sah.setLabelFor(ss_jumlah);
        l_ss_sah.setText("Jumlah Suara Sah :");

        ss_sah.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        ss_sah.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ss_sah.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                onChange(evt);
            }
        });

        l_ss_tidak_sah.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        l_ss_tidak_sah.setLabelFor(ss_jumlah);
        l_ss_tidak_sah.setText("Jumlah Suara Tidak Sah :");

        ss_tidak_sah.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        ss_tidak_sah.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ss_tidak_sah.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                onChange(evt);
            }
        });

        type.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        type.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(l_ss_jumlah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ss_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(l_ss_rusak, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ss_rusak, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(l_ss_sisa, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ss_sisa, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(l_ss_sah, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ss_sah, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(l_ss_tidak_sah, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ss_tidak_sah, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ss_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_ss_jumlah))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ss_rusak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_ss_rusak))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ss_sisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_ss_sisa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ss_sah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_ss_sah))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ss_tidak_sah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_ss_tidak_sah))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {l_ss_jumlah, l_ss_rusak, l_ss_sah, l_ss_sisa, l_ss_tidak_sah, ss_jumlah, ss_rusak, ss_sah, ss_sisa, ss_tidak_sah, type});

    }// </editor-fold>//GEN-END:initComponents

    private void onChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_onChange
        String k = (evt != null ? evt.getPropertyName() : "");

        if (! k.equals("value") || this.on_load) {
            return;
        }

		saveRekapSuara ();
    }//GEN-LAST:event_onChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel l_ss_jumlah;
    private javax.swing.JLabel l_ss_rusak;
    private javax.swing.JLabel l_ss_sah;
    private javax.swing.JLabel l_ss_sisa;
    private javax.swing.JLabel l_ss_tidak_sah;
    private javax.swing.JFormattedTextField ss_jumlah;
    private javax.swing.JFormattedTextField ss_rusak;
    private javax.swing.JFormattedTextField ss_sah;
    private javax.swing.JFormattedTextField ss_sisa;
    private javax.swing.JFormattedTextField ss_tidak_sah;
    private javax.swing.JFormattedTextField type;
    // End of variables declaration//GEN-END:variables

	private void loadData(int type) {
		QuickCount		qc	= QuickCount.getInstance();
		DatabaseManager dbm = DatabaseManager.getInstance();
		String			tname = "";
		
		if (type == 1) {
			tname = "rekap_suara_dpr";
		} else if (type == 2) {
			tname = "rekap_suara_dprd";
		}
		
		dbm.prepare (
			" select jumlah, rusak, sisa, sah, tidak_sah "
		+	" from "+ tname
		+	" where dapil_id		= ? "
		+	" and	kecamatan_id	= ? "
		+	" and	kelurahan_id	= ? "
		+	" and	tps_id			= ? "
		+	" and	kode_saksi		= ? "
		);
		
		int i = 1;
		
		try {
			dbm._ps.setInt(i++, qc.dapil_id);
			dbm._ps.setInt(i++, qc.kecamatan_id);
			dbm._ps.setInt(i++, qc.kelurahan_id);
			dbm._ps.setInt(i++, qc.tps_id);
			dbm._ps.setString(i++, qc.kode_saksi);
			dbm.executePrepare();
			
			if (dbm._rs.next()) {
				ss_jumlah.setValue(dbm._rs.getObject("jumlah"));
				ss_rusak.setValue(dbm._rs.getObject("rusak"));
				ss_sisa.setValue(dbm._rs.getObject("sisa"));
				ss_sah.setValue(dbm._rs.getObject("sah"));
				ss_tidak_sah.setValue(dbm._rs.getObject("tidak_sah"));
			}
			
			dbm.close ();
		} catch (SQLException ex) {
			Logger.getLogger(PanelRekapSuara.class.getName()).log(Level.SEVERE, null, ex);
		}

	}

	private void saveRekapSuara() {
        QuickCount		qc		= QuickCount.getInstance();
        DatabaseManager	dbm		= DatabaseManager.getInstance();
        Integer			t		= ((Number) this.type.getValue()).intValue();
        String			tname	= "";

        if (t.equals(1)) {
            tname = "rekap_suara_dpr";
        } else if (t.equals(2)) {
            tname = "rekap_suara_dprd";
        }

        dbm.prepare(" delete from "+ tname +" where tps_id = ? and kode_saksi = ? ");

		System.out.println (tname);
		
        try {
            dbm._ps.setInt (1, qc.tps_id);
            dbm._ps.setString (2, qc.kode_saksi);

            dbm._ps.executeUpdate();
            dbm.close ();
        } catch (SQLException ex) {
            Logger.getLogger(PanelRekapSuara.class.getName()).log(Level.SEVERE, null, ex);
        }

        dbm.prepare (
            " insert into "+ tname +" ("
            +	"	dapil_id, kecamatan_id, kelurahan_id, tps_id, kode_saksi"
            +	" ,	jumlah, rusak, sisa, sah, tidak_sah"
            +	" ) values ("
            +	"	?, ?, ?, ?, ?"
            +	" ,	?, ?, ?, ?, ?"
            +	" )"
        );

        try {
            int i = 1;

            dbm._ps.setInt (i++, qc.dapil_id);
            dbm._ps.setInt (i++, qc.kecamatan_id);
            dbm._ps.setInt (i++, qc.kelurahan_id);
            dbm._ps.setInt (i++, qc.tps_id);
            dbm._ps.setString (i++, qc.kode_saksi);
            dbm._ps.setInt (i++, ((Number) ss_jumlah.getValue()).intValue());
            dbm._ps.setInt (i++, ((Number) ss_rusak.getValue()).intValue());
            dbm._ps.setInt (i++, ((Number) ss_sisa.getValue()).intValue());
            dbm._ps.setInt (i++, ((Number) ss_sah.getValue()).intValue());
            dbm._ps.setInt (i++, ((Number) ss_tidak_sah.getValue()).intValue());

            dbm._ps.executeUpdate();
            dbm.close ();
        } catch (SQLException ex) {
            Logger.getLogger(PanelRekapSuara.class.getName()).log(Level.SEVERE, null, ex);
        }
	}
}
