/*
 Copyright 2014 - Mhd Sulhan (m.shulhan@gmail.com)
 */

package quickcount;

import java.awt.BorderLayout;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.ScrollPaneConstants;

/**
 *
 * @author Mhd Sulhan <m.shulhan@gmail.com>
 */
public class WinHasilPemilu extends javax.swing.JFrame {

	/**
	 * Creates new form WinHasilPemilu
	 */
	public WinHasilPemilu() {
		initComponents();
		initDPR ();
		initDPRD ();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tb_DPR = new javax.swing.JToggleButton();
        tb_DPRD = new javax.swing.JToggleButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        tp_DPR = new javax.swing.JTabbedPane();
        tp_DPRD = new javax.swing.JTabbedPane();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hasil Pemilu");
        setFocusCycleRoot(false);
        setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        setName("fHasilPemilu"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        tb_DPR.setText("DPR");
        tb_DPR.setToolTipText("");
        tb_DPR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_DPRMouseClicked(evt);
            }
        });

        tb_DPRD.setText("DPRD");
        tb_DPRD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_DPRDMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 824, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(tp_DPR, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(tp_DPRD)
                    .addContainerGap()))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addComponent(tp_DPR, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(tp_DPRD, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
                    .addGap(12, 12, 12)))
        );
        jLayeredPane1.setLayer(tp_DPR, javax.swing.JLayeredPane.DEFAULT_LAYER);

        tp_DPR.setVisible(false);
        tp_DPRD.setVisible(false);
        jLayeredPane1.setLayer(tp_DPRD, javax.swing.JLayeredPane.DEFAULT_LAYER);

        back.setText("Kembali");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(tb_DPR)
                .addGap(18, 18, 18)
                .addComponent(tb_DPRD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(back)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tb_DPR)
                    .addComponent(tb_DPRD)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tb_DPRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_DPRMouseClicked
        tb_DPRD.setSelected(false);
        tp_DPRD.setVisible(false);
        tp_DPR.setVisible(true);
    }//GEN-LAST:event_tb_DPRMouseClicked

    private void tb_DPRDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_DPRDMouseClicked
        tb_DPR.setSelected(false);
        tp_DPR.setVisible(false);
        tp_DPRD.setVisible(true);
    }//GEN-LAST:event_tb_DPRDMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
		QuickCount qc = QuickCount.getInstance();

		qc.exportHasilPemilu ();
		qc.win_saksi.setVisible(true);
		qc.win_hasil.setVisible(false);
		qc.win_hasil = null;
    }//GEN-LAST:event_backMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
		QuickCount.getInstance().exportHasilPemilu();
    }//GEN-LAST:event_formWindowClosed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JToggleButton tb_DPR;
    private javax.swing.JToggleButton tb_DPRD;
    private javax.swing.JTabbedPane tp_DPR;
    private javax.swing.JTabbedPane tp_DPRD;
    // End of variables declaration//GEN-END:variables

	private void initDPR() {
		QuickCount		qc	= QuickCount.getInstance();
		DatabaseManager dbm = DatabaseManager.getInstance();
		Integer			id;
		String			nama;

		dbm.prepare (
			" select	id"
		+	" ,			nama"
		+	" from		partai"
		);

		dbm.executePrepare();

		try {
			while (dbm._rs.next()) {
				id		= dbm._rs.getInt("id");
				nama	= dbm._rs.getString("nama");

				PreparedStatement	ps = dbm._con.prepareStatement(
						" select	1		as dpr"
					+	" ,			id		as caleg_id"
					+	" ,			caleg_dpr.partai_id"
					+	" ,			no_urut"
					+	" ,			nama"
					+	" ,			ifnull(hasil_dpr.hasil, 0) as hasil"
					+	" from		caleg_dpr"
					+	" left join	hasil_dpr"
					+	"	on	caleg_dpr.id = hasil_dpr.caleg_id"
					+	" where		caleg_dpr.dapil_id	= ?"
					+	" and		caleg_dpr.partai_id	= ?"
					);

				ps.setInt (1, qc.dapil_id);
				ps.setInt (2, id);

				ResultSet rs = ps.executeQuery();

				TableHasilPemilu	t	= new TableHasilPemilu(rs);
				JPanel				p	= new JPanel();
				JScrollPane			sp	= new JScrollPane(t
										, ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED
										, ScrollPaneConstants.HORIZONTAL_SCROLLBAR_AS_NEEDED);

				p.setLayout(new BorderLayout());
				p.add(sp, BorderLayout.CENTER);
				p.setName(nama);

				tp_DPR.add(p);

				rs.close();
				ps.close();
			}
		} catch (SQLException ex) {
			Logger.getLogger(WinHasilPemilu.class.getName()).log(Level.SEVERE, null, ex);
		}

		PanelRekapSuara rekapss = new PanelRekapSuara(1);

		tp_DPR.add (rekapss);
	}

	private void initDPRD() {
		QuickCount		qc	= QuickCount.getInstance();
		DatabaseManager dbm = DatabaseManager.getInstance();
		Integer			id;
		String			nama;

		dbm.prepare (
			" select	id"
		+	" ,			nama"
		+	" from		partai"
		);

		dbm.executePrepare();

		try {
			while (dbm._rs.next()) {
				id		= dbm._rs.getInt("id");
				nama	= dbm._rs.getString("nama");

				PreparedStatement	ps = dbm._con.prepareStatement(
						" select	2		as dprd"
					+	" ,			id		as caleg_id"
					+	" ,			caleg_dprd.partai_id"
					+	" ,			no_urut"
					+	" ,			nama"
					+	" ,			ifnull(hasil_dprd.hasil, 0) as hasil"
					+	" from		caleg_dprd"
					+	" left join	hasil_dprd"
					+	"	on	caleg_dprd.id = hasil_dprd.caleg_id"
					+	" where		caleg_dprd.dapil_id = ?"
					+	" and		caleg_dprd.partai_id = ?"
					);

				ps.setInt (1, qc.dapil_id);
				ps.setInt (2, id);

				ResultSet rs = ps.executeQuery();

				TableHasilPemilu	t	= new TableHasilPemilu (rs);
				JPanel				p	= new JPanel();
				JScrollPane			sp	= new JScrollPane(t
										, ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED
										, ScrollPaneConstants.HORIZONTAL_SCROLLBAR_AS_NEEDED);

				p.setLayout(new BorderLayout());
				p.add(sp, BorderLayout.CENTER);
				p.setName(nama);

				tp_DPRD.add(p);

				rs.close();
				ps.close();
			}
		} catch (SQLException ex) {
			Logger.getLogger(WinHasilPemilu.class.getName()).log(Level.SEVERE, null, ex);
		}

		PanelRekapSuara rekapss = new PanelRekapSuara(2);

		tp_DPRD.add (rekapss);

	}
}
